# Generated by Django 6.1 on 2026-08-16 21:15

import django.core.validators
import django.db.models.deletion
import posterizer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پروفایل')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه')),
                ('num_layers', models.PositiveSmallIntegerField(default=4, help_text='عددی بین 2 تا 16', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(16)], verbose_name='تعداد لایه\u200cها')),
                ('is_active', models.BooleanField(default=True, help_text='پروفایل\u200cهای غیرفعال به کاربران نمایش داده نمی\u200cشوند.', verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر، بالاتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پروفایل رنگی',
                'verbose_name_plural': 'پروفایل\u200cهای رنگی',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=100, verbose_name='نام پروفایل (ثبت\u200cشده)')),
                ('num_layers', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد لایه\u200cها')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='رنگ لایه\u200cها')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات پردازش')),
                ('original_image', models.FileField(blank=True, upload_to=posterizer.models.original_upload_path, verbose_name='تصویر اصلی')),
                ('result_image', models.FileField(upload_to=posterizer.models.result_upload_path, verbose_name='تصویر نهایی')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات کاربر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='posterizer.colorprofile', verbose_name='پروفایل رنگی')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='از ۰ شروع می\u200cشود؛ لایهٔ ۰ تیره\u200cترین ناحیه است.', verbose_name='شمارهٔ لایه')),
                ('color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{6})$', 'رنگ باید به شکل کد هگز شش\u200cرقمی باشد. نمونه: #1a2b3c')], verbose_name='رنگ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='posterizer.colorprofile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'لایهٔ رنگی',
                'verbose_name_plural': 'لایه\u200cهای رنگی',
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'index'), name='unique_layer_index_per_profile')],
            },
        ),
    ]
