# Generated by Django 6.1 on 2026-08-16 22:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0002_seed_color_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_width_cm', models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6, verbose_name='حداقل عرض (سانتی\u200cمتر)')),
                ('max_width_cm', models.DecimalField(decimal_places=1, default=Decimal('100.0'), max_digits=6, verbose_name='حداکثر عرض (سانتی\u200cمتر)')),
                ('min_height_cm', models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6, verbose_name='حداقل ارتفاع (سانتی\u200cمتر)')),
                ('max_height_cm', models.DecimalField(decimal_places=1, default=Decimal('100.0'), max_digits=6, verbose_name='حداکثر ارتفاع (سانتی\u200cمتر)')),
                ('price_per_cm2', models.PositiveIntegerField(default=5000, help_text='برآورد هزینه = مساحت قاب (سانتی\u200cمتر مربع) × این عدد', verbose_name='قیمت هر سانتی\u200cمتر مربع (تومان)')),
                ('cost_rounding', models.PositiveIntegerField(default=1000, help_text='مبلغ برآوردی به نزدیک\u200cترین مضرب این عدد گرد می\u200cشود.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='گرد کردن مبلغ به (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='area_cm2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مساحت (سانتی\u200cمتر مربع)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_cost',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='هزینهٔ برآوردی (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_cost',
            field=models.PositiveBigIntegerField(blank=True, help_text='پس از بررسی، مبلغ قطعی را اینجا وارد کنید. خالی بماند یعنی همان مبلغ برآوردی.', null=True, verbose_name='هزینهٔ نهایی (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='ارتفاع قاب (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_per_cm2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت هر سانتی\u200cمتر مربع هنگام ثبت (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='عرض قاب (سانتی\u200cمتر)'),
        ),
    ]
