# Generated by Django 6.1 on 2026-08-16 22:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0004_seed_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_bilateral_d',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='قطر فیلتر دوطرفه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_bilateral_sigma_color',
            field=models.FloatField(default=45.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='سیگما رنگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_bilateral_sigma_space',
            field=models.FloatField(default=45.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='سیگما مکان'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_gaussian_kernel_size',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='اندازه کرنل گاوسی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_majority_window_size',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='اندازه پنجره اکثریت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_median_kernel_size',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='اندازه کرنل میانه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_min_region_size',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='حداقل اندازه ناحیه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_morph_kernel_size',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='اندازه کرنل مورفولوژی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_postprocess_method',
            field=models.CharField(choices=[('none', 'بدون پاک\u200cسازی'), ('median', 'فیلتر میانه'), ('morphology', 'مورفولوژی'), ('connected_components', 'مؤلفه\u200cهای همبند'), ('majority_filter', 'فیلتر اکثریت')], default='connected_components', max_length=30, verbose_name='روش پاک\u200cسازی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_preprocess_method',
            field=models.CharField(choices=[('none', 'بدون هموارسازی'), ('gaussian', 'محو گاوسی'), ('median', 'فیلتر میانه'), ('bilateral', 'دوطرفه (حفظ لبه\u200cها)')], default='bilateral', max_length=20, verbose_name='روش هموارسازی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_preserve_edges',
            field=models.BooleanField(default=True, verbose_name='حفظ لبه\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_profile',
            field=models.ForeignKey(blank=True, help_text='خالی بماند یعنی اولین پروفایل فعال بر اساس ترتیب نمایش.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posterizer.colorprofile', verbose_name='پروفایل رنگی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_superpixel_region_size',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='اندازه ناحیه سوپرپیکسل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_use_superpixels',
            field=models.BooleanField(default=False, verbose_name='استفاده از سوپرپیکسل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stl_invert_heights',
            field=models.BooleanField(default=False, help_text='به\u200cطور پیش\u200cفرض روشن\u200cترین لایه بلندترین است. با فعال کردن این گزینه، تیره\u200cترین لایه بلندترین می\u200cشود.', verbose_name='وارونه کردن ارتفاع لایه\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stl_layer_height_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='لایهٔ ۱ به این اندازه، لایهٔ ۲ دو برابر، لایهٔ ۳ سه برابر و … ارتفاع می\u200cگیرد.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.05'))], verbose_name='ارتفاع هر لایه (میلی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stl_max_resolution',
            field=models.PositiveIntegerField(default=400, help_text='بزرگ\u200cترین ضلع مدل به این تعداد سلول تقسیم می\u200cشود. عدد بزرگ\u200cتر = جزئیات بیشتر و فایل سنگین\u200cتر.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)], verbose_name='حداکثر دقت مدل سه\u200cبعدی (پیکسل)'),
        ),
    ]
