# Generated by Django 6.1 on 2026-08-18 20:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0005_sitesettings_default_bilateral_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('studio', 'ساخته\u200cشده با ابزار سایت'), ('ready', 'تصویر آمادهٔ کاربر')], db_index=True, default='studio', max_length=10, verbose_name='منبع تصویر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_helper_enabled',
            field=models.BooleanField(default=True, verbose_name='نمایش راهنمای ساخت با هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_helper_model_name',
            field=models.CharField(blank=True, default='Nano Banana Pro', max_length=100, verbose_name='نام مدل پیشنهادی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_helper_prompt',
            field=models.TextField(blank=True, default='Convert this photo into a flat, poster-style illustration made of exactly 4 solid colors.\n\nStrict rules:\n- Use ONLY 4 distinct flat colors. No gradients, no shading, no texture, no noise, no dithering.\n- Every region must be one uniform color with hard, clean edges.\n- Keep the subject clearly recognizable; simplify detail into the 4 tonal levels from darkest to lightest.\n- Keep the original aspect ratio and framing.\n- Output a single image, no text, no watermark, no border.\n', help_text='متنی که کاربر کپی می\u200cکند و همراه عکسش به مدل هوش مصنوعی می\u200cدهد.', verbose_name='پرامپت پیشنهادی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_helper_url',
            field=models.URLField(blank=True, verbose_name='لینک مدل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ready_images_enabled',
            field=models.BooleanField(default=True, help_text='اگر خاموش شود، کاربران فقط می\u200cتوانند با ابزار خود سایت تصویر بسازند.', verbose_name='پذیرش تصاویر آماده'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ready_max_colors',
            field=models.PositiveSmallIntegerField(default=16, help_text='تصویر آماده\u200cای که بیش از این تعداد لایه داشته باشد پذیرفته نمی\u200cشود.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(16)], verbose_name='حداکثر تعداد رنگ مجاز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ready_min_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.00'), help_text='اگر رنگ\u200cهای اصلی کمتر از این مقدار از تصویر را بپوشانند، تصویر طیف\u200cدار است و رد می\u200cشود.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('50.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='حداقل پوشش رنگ\u200cهای اصلی (درصد)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ready_min_layer_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='رنگ\u200cهایی که کمتر از این مقدار از تصویر را بگیرند، لایهٔ مستقل به حساب نمی\u200cآیند.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='حداقل سهم هر لایه (درصد)'),
        ),
    ]
