# Generated by Django 6.1, then hand-edited to carry the data change too.

from django.db import migrations, models

from posterizer.prompts import DEFAULT_AI_PROMPT

# The placeholder shipped in 0006, recognised so an admin's own wording is kept.
OLD_PLACEHOLDER_START = "Convert this photo into a flat, poster-style illustration"


def adopt_new_prompt(apps, schema_editor):
    """
    Move the existing settings row onto the new prompt.

    Changing a field default only affects rows created afterwards, and the
    singleton already exists — so without this the site would keep serving the
    old placeholder. Only a blank value or the previous placeholder is
    replaced; wording an admin typed themselves is left alone.
    """
    SiteSettings = apps.get_model("posterizer", "SiteSettings")
    row = SiteSettings.objects.filter(pk=1).first()
    if row is None:
        return

    current = (row.ai_helper_prompt or "").strip()
    if current and not current.startswith(OLD_PLACEHOLDER_START):
        return

    row.ai_helper_prompt = DEFAULT_AI_PROMPT
    row.save(update_fields=["ai_helper_prompt"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("posterizer", "0006_order_source_sitesettings_ai_helper_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="ai_helper_prompt",
            field=models.TextField(blank=True, default=DEFAULT_AI_PROMPT, help_text='متنی که کاربر کپی می\u200cکند و همراه عکسش به مدل هوش مصنوعی می\u200cدهد.', verbose_name='پرامپت پیشنهادی'),
        ),
        migrations.RunPython(adopt_new_prompt, noop),
    ]
