# Generated by Django 6.1 on 2026-08-18 21:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0008_stl_dark_is_tallest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='stl_layer_height_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='ارتفاع پایه. هر لایه مضربی از این عدد است؛ با ۴ لایه و ۲ میلی\u200cمتر، ارتفاع\u200cها ۸، ۶، ۴ و ۲ میلی\u200cمتر می\u200cشود (از تیره به روشن).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.05'))], verbose_name='ارتفاع هر لایه (میلی\u200cمتر)'),
        ),
    ]
