# Generated by Django 6.1 on 2026-08-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0009_stl_layer_height_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gallery_caption',
            field=models.CharField(blank=True, help_text='اگر خالی بماند، نام پروفایل رنگی نمایش داده می\u200cشود.', max_length=80, verbose_name='عنوان در گالری'),
        ),
        migrations.AddField(
            model_name='order',
            name='gallery_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر، جلوتر نمایش داده می\u200cشود.', verbose_name='ترتیب در گالری'),
        ),
        migrations.AddField(
            model_name='order',
            name='in_gallery',
            field=models.BooleanField(db_index=True, default=False, help_text='فقط تصویر لایه\u200cای نمایش داده می\u200cشود، نه عکس اصلی کاربر.', verbose_name='نمایش در گالری صفحهٔ اصلی'),
        ),
    ]
