# Generated by Django 6.1 on 2026-08-19 18:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posterizer', '0010_order_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stl_border_min_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='برای قاب\u200cهای کوچک، ضخامت هرگز کمتر از این مقدار نمی\u200cشود.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='حداقل ضخامت قاب (میلی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stl_border_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('3.0'), help_text='نسبت به کوچک\u200cترین ضلع تصویر محاسبه می\u200cشود و به بیرون اضافه می\u200cگردد؛ ارتفاع قاب برابر بلندترین لایه است. صفر یعنی بدون قاب.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='ضخامت قاب دور تصویر (درصد)'),
        ),
    ]
